# Generated by Django 6.0.4 on 2026-05-19 18:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_user_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=django.contrib.auth.models.User, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
