# Generated by Django 6.0.4 on 2026-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu/default.jpg', upload_to='menu/'),
        ),
    ]
