# Generated by Django 6.0.4 on 2026-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='menu/'),
        ),
    ]
