# Generated by Django 6.0.4 on 2026-06-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_featured_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Category',
            new_name='category',
        ),
    ]
