# Generated by Django 6.0.4 on 2026-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_category_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='images/favicon_io/favicon-32x32.png', null=True, upload_to='menu/'),
        ),
    ]
